title:  Mailův blog
description: 'Blog o počítačích postupech a tak vůbec'
url:    http://www.rooland.cz
permalink:  /:year/:month/:day/:title.html
timezone: '+01:00'

disqus_shortname: mailuv-blog-rooland

exclude: CNAME, Gemfile, Gemfile.lock, Rakefile.rb, README, tasks